# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U58LoqnCunes2X0VlRvAUIgb0XMfWODh
"""

a=2
b=5
print(a+b)
print(a*b)

